<form method="post" action="/crud/add">
    <div class="mb-5">
        <label class="w-50">
            <input class="form-control" name="title" placeholder="Title">
        </label>
    </div>
    <div class="mb-5">
        <label class="w-50">
            <input class="form-control" name="description" placeholder="Description">
        </label>
    </div>
    <div class="mb-5">
        <label class="w-50">
            <button type="submit" class="btn btn-light w-100">Add</button>
        </label>
    </div>
</form>