<?php use Core\Views\View; ?>
<!DOCTYPE html>
<html lang="en-us" class="h-100">
<head>
    <meta charset="utf-8">
    <meta name="theme-color" content="#7952b3">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="<?= View::staticFile('css/style.css') ?>">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="icon" href="/">
    <title>YoORK - PHP MicroFramework</title>
</head>
<body class="d-flex h-100 text-center text-white bg-dark">
<div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
    <header class="mb-auto">
        <div>
            <a class="text-white" href="/" rel="noopener noreferrer">
                <h3 class="float-md-start mb-0">YoORK</h3>
            </a>
            <nav class="nav nav-masthead justify-content-center float-md-end">
                <a class="nav-link" href="/" rel="noopener noreferrer">Home</a>
                <a class="nav-link" href="/crud" rel="noopener noreferrer">CRUD</a>
                <a class="nav-link" href="https://gitlab.com/ulissesjdeo1/yoork" target="_blank" rel="noopener noreferrer">GitLab</a>
            </nav>
        </div>
    </header>
    <main class="px-3">
        <?= $this->content() ?>
    </main>
    <footer class="mt-auto text-white-50">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
    </footer>
</div>
</body>
</html>